-- Tracked parlays generated by the AI
create table if not exists parlays (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  legs jsonb not null,
  combined_odds text not null,
  combined_decimal numeric not null,
  ev numeric not null,
  ev_percent numeric not null,
  confidence integer not null,
  payout numeric not null,
  stake numeric default 100,
  status text default 'pending' check (status in ('pending', 'won', 'lost', 'push', 'partial')),
  result_checked_at timestamptz,
  legs_won integer default 0,
  legs_lost integer default 0,
  legs_total integer not null,
  sports text[] not null,
  profit numeric default 0
);

-- Index for querying by status and date
create index if not exists idx_parlays_status on parlays(status);
create index if not exists idx_parlays_created on parlays(created_at desc);

-- Daily summary stats (materialized for fast reads)
create table if not exists daily_stats (
  date date primary key,
  parlays_generated integer default 0,
  parlays_won integer default 0,
  parlays_lost integer default 0,
  total_staked numeric default 0,
  total_returned numeric default 0,
  profit numeric default 0,
  win_rate numeric default 0,
  roi numeric default 0,
  updated_at timestamptz default now()
);

-- Enable RLS
alter table parlays enable row level security;
alter table daily_stats enable row level security;

-- Public read access (everyone can see the track record)
create policy "Public read parlays" on parlays for select using (true);
create policy "Public read daily_stats" on daily_stats for select using (true);

-- Only service role can insert/update (API routes)
create policy "Service insert parlays" on parlays for insert with check (true);
create policy "Service update parlays" on parlays for update using (true);
create policy "Service insert daily_stats" on daily_stats for insert with check (true);
create policy "Service update daily_stats" on daily_stats for update using (true);
