-- v1 LAUNCH RESET — run once in Supabase SQL editor.
--
-- Context: pre-launch development accumulated ~253 tracked AI parlays and
-- user sim bets generated by early model versions that had several bugs
-- (fake confidence math, no spread/totals model, stale-game leakage,
-- juice-pile Lock of Day picks). All those bugs are fixed.
--
-- No one's used the app publicly yet, so the cleanest move is to wipe
-- the accumulated data and launch with a clean track record.
--
-- This clears:
--   - parlays            → the public AI track record
--   - sim_parlays        → user-placed sim bets
--   - line_history       → historical line snapshots
-- And resets bankrolls back to each user's starting_balance.
--
-- Subscriptions, achievements, referrals, email captures, and user
-- accounts are left untouched.

BEGIN;

TRUNCATE TABLE parlays RESTART IDENTITY CASCADE;
TRUNCATE TABLE sim_parlays RESTART IDENTITY CASCADE;
TRUNCATE TABLE line_history RESTART IDENTITY CASCADE;

UPDATE sim_bankroll
SET
  balance = starting_balance,
  total_wagered = 0,
  total_won = 0,
  total_lost = 0,
  wins = 0,
  losses = 0,
  updated_at = NOW();

COMMIT;
